<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup>  <UserSecretsId>31e82f89-341c-4168-9d13-ad3dcfe621f7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Erp.Application\Erp.Application.csproj" />
    <ProjectReference Include="..\Erp.Infrastructure\Erp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
